### ISSUE TITLE
Serve password fields over https 

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/Check-In#99]
Firefox and chrome are now warning about GSI password fields over http, so we should switch to https. This would be easy with dokku

**Comment by Sumukh** [comment]
Is the check in app on dokku? If so it should just be `dokku letsencrypt dokku` 

```
$ dig la.cs61a.org
la.cs61a.org.		1620	IN	CNAME	checkin.colinschoen.me.
```

**Comment by colinschoen** [comment]
Fixed.
